### ISSUE TITLE
Sample will not fail gracefully on speaker devices

### ISSUE THREAD

**Issue by arunjeetsingh** [alexa-labs/skill-sample-nodejs-pager-karaoke#1]
On speaker devices that don't support APL, the current sample will fail with "...there is a problem with the skill response...". Instead, the sample should detect APL support on a device and if it isn't found, provide a reasonable failover experience explaining that the sample is meant for a multimodal Alexa device.

Repo maintainer(s), please see alexa-labs/skill-sample-nodejs-firetv-vlogs#3 for how to fix this issue.

**Comment by CamiWilliams** [comment]
Done!
